name: '@hectorjs/stub-cli'

on:
  push:
    branches:
      - master
      - development
      - feature/#26
  schedule:
    - cron:  '0 8 * * *'

jobs:
  build:
    name: Stub-cli

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 10.x , 12.x ]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Unit test & coverage
      run: |
        npm install
        npm run coverage
      env:
        CI: true
    - name: End to end
      run: |
        npm install
        npm run e2e
      env:
        CI: true
    - name: Code quality
      run: |
        npm run eslint
      env:
        CI: true
    - name: Audit
      run: |
        npm audit
      env:
        CI: true
    - name: Publish resport coverage
      run: |
        npm -g i codecov@3.6.1
        npm run report-coverage -- -t ${{ secrets.CODECOV_TOKEN }}
      env:
        CI: true
        


        
