name: 'eslint-config-google'

on:
  push:
    branches:
      - master
      - development
  schedule:
    - cron:  '0 8 * * *'

jobs:
  build:
    name: Stub-cli

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [ 10.x , 12.x ]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Code quality
      run: |
        npm ci
        npm run eslint
      env:
        CI: true
        
